#!/bin/bash
set -ouex pipefail

SENTINEL=/var/lib/bees-first-boot-done

if [[ -f "$SENTINEL" ]]; then
    echo "bees already configured, skipping."
    exit 0
fi

# Resolve the root filesystem UUID from the label
UUID=$(findmnt -n -o UUID /)

if [[ -z "$UUID" ]]; then
    echo "ERROR: Could not determine root filesystem UUID" >&2
    exit 1
fi

echo "Configuring bees for root filesystem UUID: $UUID"

# Create bees config
mkdir -p /etc/bees
cat > "/etc/bees/${UUID}.conf" <<EOF
# Bees configuration for root filesystem
# Generated by first-boot setup
UUID=$UUID
DB_SIZE=$((256 * 1024 * 1024))
EOF

# Enable and start beesd for this filesystem
systemctl enable --now "beesd@${UUID}.service"

# Mark first-boot setup as complete
touch "$SENTINEL"
echo "bees setup complete."
